import { Anek_Latin } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";


//const carnas = localFont({src: '../assets/fonts/carnas_light.woff',subsets: ['latin']})

//export const carnas_medium = localFont({src: '../assets/fonts/carnas_medium.woff',subsets: ['latin']})

    const anek = Anek_Latin({ subsets: ["latin"],weight:['300','400','500','700'] });

export const metadata = {
  title: "JEVA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body  className={anek.className}>
      <main className="relative">
      <Navbar/>

        {children}
        <Footer/>
      
      </main>
      </body>
    </html>
  );
}
